-- PRD-23: Framework Tags & Browse Frameworks
-- Add topic tags to ai_frameworks for filtering and Browse Frameworks view

ALTER TABLE ai_frameworks
  ADD COLUMN IF NOT EXISTS tags TEXT[] NOT NULL DEFAULT '{}';

CREATE INDEX IF NOT EXISTS idx_ai_frameworks_tags
  ON ai_frameworks USING GIN (tags);

COMMENT ON COLUMN ai_frameworks.tags IS
  'Topic tags auto-generated by manifest-tag-framework Edge Function (Haiku) after save. User-editable from FrameworkPrinciples.';
